#!/bin/bash

# Usage: run_pylint [code directory]

#  TODO: Make this work with python3 code

CODEDIR=$1

if [ $# -lt 1 ]
then
    echo "Usage: run_pylint CODEDIR [logfile]"
    exit 1
fi

if [ $# -ge 2 ]
then
    logbase1=$1
else
    logbasename=`date "+pylint_%Y%m%d-%H%M_"`
    logbase1="${logbasename}_cwd.log"
fi
S0=`basename $0`

PYLINT=pylint
#PYLINT_FLAGS="superfluous-parens"
PYLINT_FLAGS="--reports=n"

# Tee append verbose
TEEA=" | tee -a"
# Tee append quiet
#TEEA = " >> "

# Run linter from the file's current working directory

logfile1=`pwd`/$logbase1
echo "$S0: Logging to $logfile1"
for FILE in `find "$1" -iname '*.py'`
do
    D1=`dirname $FILE`
    F1=`basename $FILE`
    echo "$S0: Running pylint on $FILE" >> $logfile1
    pwd
    pushd "$D1"
    stdbuf -o 0 $PYLINT $PYLINT_FLAGS $F1 >> $logfile1
    popd
done

echo "$S0: Logged to $logfile1"
wc -l $logfile1
