#!/bin/bash

# Clone an external repository and set the checked-out version to a particular stable revision

D0=`dirname $0`


if [ ! -d $D0/rsr ]
then
    git clone https://github.com/cgrima/rsr.git
fi

# Check out stable revision
git --git-dir $D0/rsr/.git --work-tree=$D0/rsr checkout 017ac84924155eae7208adfd685f46c1afc26043


if [ ! -d $D0/subradar ]
then
    git clone https://github.com/cgrima/subradar
fi

git --git-dir $D0/subradar/.git --work-tree=$D0/subradar checkout 4d44e74a6ce3741e3f63a2ae275f6265bd788894
