#!/bin/bash

# Clone an external repository and set the checked-out version to a particular stable revision

D0=`dirname $0`


if [ ! -d $D0/rsr ]
then
    git clone https://github.com/cgrima/rsr.git
fi

# Check out stable revision
git --git-dir $D0/rsr/.git --work-tree=$D0/rsr checkout 94edf185465ce2e5719bf6aaa0fd9e5e8acac419


if [ ! -d $D0/subradar ]
then
    git clone https://github.com/cgrima/subradar
fi

git --git-dir $D0/subradar/.git --work-tree=$D0/subradar checkout fae4b33325732cf08daf1a265d092d9aa8c5aeca
